set_property PACKAGE_PIN H2 [get_ports {dm1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[0]}]
set_property PACKAGE_PIN D2 [get_ports {dm1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[1]}]
set_property PACKAGE_PIN E2 [get_ports {dm1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[2]}]
set_property PACKAGE_PIN F3 [get_ports {dm1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[3]}]
set_property PACKAGE_PIN F4 [get_ports {dm1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[4]}]
set_property PACKAGE_PIN D3 [get_ports {dm1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[5]}]
set_property PACKAGE_PIN E3 [get_ports {dm1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[6]}]
set_property PACKAGE_PIN D4 [get_ports {dm1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm1[7]}]

set_property PACKAGE_PIN D5 [get_ports {dm2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm2[0]}]
set_property PACKAGE_PIN B2 [get_ports {dm2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm2[1]}]
set_property PACKAGE_PIN B3 [get_ports {dm2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm2[2]}]
set_property PACKAGE_PIN A1 [get_ports {dm2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm2[3]}]
set_property PACKAGE_PIN B1 [get_ports {dm2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm2[4]}]
set_property PACKAGE_PIN A3 [get_ports {dm2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm2[5]}]
set_property PACKAGE_PIN A4 [get_ports {dm2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm2[6]}]
set_property PACKAGE_PIN B4 [get_ports {dm2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm2[7]}]

set_property PACKAGE_PIN G6 [get_ports {wm1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[0]}]
set_property PACKAGE_PIN E1 [get_ports {wm1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[1]}]
set_property PACKAGE_PIN F1 [get_ports {wm1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[2]}]
set_property PACKAGE_PIN G1 [get_ports {wm1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm1[3]}]

set_property PACKAGE_PIN H1 [get_ports {wm2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm2[0]}]
set_property PACKAGE_PIN C1 [get_ports {wm2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm2[1]}]
set_property PACKAGE_PIN C2 [get_ports {wm2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm2[2]}]
set_property PACKAGE_PIN G2 [get_ports {wm2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm2[3]}]

set_property PACKAGE_PIN K2 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN J2 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property PACKAGE_PIN J3 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN H4 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN J4 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]



set_property PACKAGE_PIN M1 [get_ports {les[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {les[0]}]
set_property PACKAGE_PIN K3 [get_ports {les[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports les[1]]



set_property PACKAGE_PIN R1 [get_ports {K[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {K[7]}]
set_property PACKAGE_PIN N4 [get_ports {K[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {K[6]}]
set_property PACKAGE_PIN M4 [get_ports {K[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {K[5]}]
set_property PACKAGE_PIN R2 [get_ports {K[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {K[4]}]
set_property PACKAGE_PIN P2 [get_ports {K[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {K[3]}]
set_property PACKAGE_PIN P3 [get_ports {K[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {K[2]}]
set_property PACKAGE_PIN P4 [get_ports {K[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {K[1]}]
set_property PACKAGE_PIN P5 [get_ports {K[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {K[0]}]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {K[0]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {K[1]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {K[2]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {K[3]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {K[4]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {K[5]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {K[6]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {K[7]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rkey]


## CLK
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN T5 [get_ports rs]
set_property IOSTANDARD LVCMOS33 [get_ports rs]
set_property PACKAGE_PIN U3 [get_ports rkey]
set_property IOSTANDARD LVCMOS33 [get_ports rkey]